# Generated by Django 2.2.4 on 2019-10-02 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choicetext',
            new_name='choice_text',
        ),
    ]
